### PR TITLE
PS, AE - send actual context when another webserver is running

### PR DESCRIPTION
**Pull request by kalisp**
For cases that app is already running, but same app is triggered again from launcher or FTrack to save booting time

Requires:
https://github.com/pypeclub/OpenPype/pull/1811

How to test:
-------------
Open PS via Ftrack (or launcher) from one asset
Keep PS open
Try to open PS via FTrack (or launcher) from different asset
  - it should log that is sending context change, original PS is kept open, context should be changed (check after publish if representation were added to correct asset)

For PS it doesn't solve an issue that artist would switch between multiple opened workfiles. (AE doesn't allow that.)
Validator was added for PS to compare expected context with current, artist is informed and can decide to fix (replace) context, or reopen workfile via Workfiles app to refresh context.

### CODE REVIEW

**Comment by mkolar** [comment]
@kalisp is this ready for review?

**Comment by 64qam** [comment]
It opens another work file as a new tab in Photoshop. Pyblisher shows the right context during the publishing. However, the final publishing goes to the wrong asset. Loader, creator and workfile do not change their context as well.

**Comment by kalisp** [comment]
It is not possible to capture switching between open files in PS and current implementation handles only first additional open. 
Context needs to be somehow queried from workfile, as storing it in metadata or querying it from DB.

**Comment by kalisp** [comment]
Change of context in Loader/Workfiles cannot be done reliably.

Added better validation and documentation to protect from most severe issue, eg. publishing to wrong asset.

Current customer request is solved by this, might be revisited if it would be causing problems.

**Review by 64qam — APPROVED** [review]

**Pull request merged**
