### PR TITLE
SceneInventory: Choose loader in asset switcher

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Description
Add option to choose from different loaders in switch dialog.

## Changes
- added function `get_loader_identifier` to extract loader identifier (name)
- switch function may expect loader which will be used for switching
- switch dialog changes
    - new method to get representation ids for currently context (selected containers and combobox values)
    - have option to show menu popup if there are multiple loaders that can be used for loading
        - loaders must match for all representations retrieved from currentl context of dialog
        - loaders must have `switch` method available
        - loaders with attribute `is_utility` set to True are skipped
   - first option of menu is to `Use origin loaders` which will use loaders from containers
   - the menu is not available if there is only one available loader which is same as for all containers

### Notes
- label `Use origin loaders` probably won't make sense for artists (feel free to modify)
- should be menu showed all the time and show only the loader same for all containers?
- stylesheet for arrow in pushbutton is not the best (arrow is over the icon) not sure how to fix and not break other tools
    - suggestion: move sceneinvetory to openpype tools and refactor the ui creation which would help to handle that easier

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [OP-1215 Asset switcher choose loader](https://app.clickup.com/t/6658547/OP-1215)

**Comment by kalisp** [comment]
Menu shows up only when I do not select loader, afterwards the menu never shows up again (even on same asset, so it should  have multiple loaders available.)

**Review by kalisp — CHANGES_REQUESTED** [review]
Menu shows up only when I do not select loader, afterwards the menu never shows up again (even on same asset, so it should have multiple loaders available.)

**Comment by iLLiCiTiT** [comment]
Changing of combobox values does not resolve loaders in right way.

**Comment by iLLiCiTiT** [comment]
> Changing of combobox values does not resolve loaders in right way.

Should be resolved now. There were few bugs in the code and coletelly missing condition for cases when only representation is selected in comboboxes.

**Review by mkolar — COMMENTED** [review]
The loaders seem to show correctly, however the actually switching fails. Whatever combination I use its not successful, but hard to tell how much of that is incompatibility of loaders and how much is this PR. 
image

**Review by mkolar — CHANGES_REQUESTED** [review]
I'd change the approach a tiny bit. Adding a dropdown arrow next to the button that allows to choose loader, But in case of just clicking the tickbox, the original should be used. That also eliminates the awkward `use original loader` option that might be a bit tricky to understand. 

image

**Comment by iLLiCiTiT** [comment]
> The loaders seem to show correctly, however the actually switching fails. Whatever combination I use its not successful, but hard to tell how much of that is incompatibility of loaders and how much is this PR.

Looks like invalid container...

> I'd change the approach a tiny bit. Adding a dropdown arrow next to the button that allows to choose loader

Modified. It was confusing now anyway...

**Comment by mkolar** [comment]
The base of it works, however, most loader are of course not compatible, so it's possible we'll get more false reports of bugs. On the other had we'll at least uncover what kind of usage it people will try to trigger with it.

**Review by mkolar — APPROVED** [review]

**Review by kalisp — APPROVED** [review]
Menu shows as expected.

**Pull request merged**
