### PR TITLE
Cache plugins.

### PR DESCRIPTION
**Pull request by tokejepsen**
**Goal**

To cache plugins for later use.

**Motivation**

There is currently no way of getting already registered plugins without running `api.discover`. When doing this inside a plugin it results in that instance of the plugin getting flushed from memory. An example of this:

```python
from avalon import api, io


class ProjectionLoader(api.Loader):
    """
    This will load camera, pointcache and image to build a projection setup.
    """

    families = ["projection"]
    representations = ["json"]

    label = "Load Projection"
    icon = "camera"
    color = "orange"
    node_color = "0x3469ffff"

    def load(self, context, name, namespace, data):
        api.discover(api.Loader)
        print(io.find_one({"_id": context["asset"]["_id"]}))
```

**Implementation**

Currently the cached plugins from the last `api.discover` call is stored under `api.registered_plugins`. This naming convention is up for discussion. @BigRoy has mentioned these alternatives; `api.cached_plugins` and `api.last_discovered_plugins`.

The data structure of the stored plugins is a dictionary with the superclass' name as key and the discovered plugins as values;
```
{'Loader': [<class 'load_camera_abc.AlembicCameraLoader'>, <class 'load_pointcache_abc.AlembicPointcacheLoader'>, <class 'copy_file.CopyFile'>, <class 'copy_file_path.CopyFilePath'>, <class 'load_script_precomp.LinkAsGroup'>, <class 'load_backdrop.LoadBackdropNodes'>, <class 'load_gizmo.LoadGizmo'>, <class 'load_gizmo_ip.LoadGizmoInputProcess'>, <class 'load_image.LoadImage'>, <class 'load_luts.LoadLuts'>, <class 'load_luts_ip.LoadLutsInputProcess'>, <class 'load_mov.LoadMov'>, <class 'load_sequence.LoadSequence'>, <class 'load_matchmove.MatchmoveLoader'>, <class 'open_djv.OpenInDJV'>, <class 'open_file.Openfile'>, <class 'load_projection.ProjectionLoader'>, <class 'actions.SetFrameRangeLoader'>, <class 'actions.SetFrameRangeWithHandlesLoader'>]}
```

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
>@BigRoy has mentioned these alternatives

I agree `registered` says that it was registered by pipeline and should be discovered on discover but this is cache of discover. I like `last_discovered_plugins` as it is totally describing what it is.

**Comment by tokejepsen** [comment]
> This workaround example also works. Note the extra import in the load() method.

The example does work, but as I experienced when you come to containerising there arent any workarounds as far I as could gather.

**Comment by BigRoy** [comment]
> The example does work, but as I experienced when you come to containerising there arent any workarounds as far I as could gather.

Sorry, could you describe that particular issue and where it fails? I'm not seeing where this *cached plug-ins* solves that either.

**Comment by tokejepsen** [comment]
> Sorry, could you describe that particular issue and where it fails? I'm not seeing where this cached plug-ins solves that either.
The import for the function that containerizes should also be imported locally - if that's what was failing for you.

Sorry, ignore me. Tried to reproduce the issue, but I cant now. Might just have been development mess.

**Comment by mkolar** [comment]
Is this still relevant @tokejepsen ? @iLLiCiTiT could I get and eye on this please

**Comment by tokejepsen** [comment]
I would say so yeah. Having to import within the the plugins is very confusing. Either way it needs to be documented how to use `api.discover` within a plugin correctly.

**Comment by iLLiCiTiT** [comment]
> @iLLiCiTiT could I get and eye on this please

Already looked. I don't understand the use case of using a plugin inside a plugin but code seems to be ok for me.

**Comment by tokejepsen** [comment]
> Already looked. I don't understand the use case of using a plugin inside a plugin but code seems to be ok for me.

Its to reuse code/plugins. The use case that originated this was the projection workflow that requires to publish/load camera and pointcaches, both of which are good to have as individual publishes and loaders.

**Comment by iLLiCiTiT** [comment]
> as individual publishes and loaders.

So you want to have one loader that will trigger 2 or more different loaders?

**Comment by tokejepsen** [comment]
> So you want to have one loader that will trigger 2 or more different loaders?

Yeah, this is how the projection workflow is proposed atm. Because we need multiple components to come together, those components can be re-used individually.

https://github.com/pypeclub/pype/pull/1110/files#diff-95d4c7766d34e9056c6457692c8c681e3e532045b2a848d87ffb864021aa2e14

**Review by mkolar — APPROVED** [review]

**Pull request merged**
